
package pos;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "pos_tag", targetNamespace = "http://pos/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PosTag {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "tag_word")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "tag_word", targetNamespace = "http://pos/", className = "pos.TagWord")
    @ResponseWrapper(localName = "tag_wordResponse", targetNamespace = "http://pos/", className = "pos.TagWordResponse")
    @Action(input = "http://pos/pos_tag/tag_wordRequest", output = "http://pos/pos_tag/tag_wordResponse")
    public String tagWord(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
