
package pos;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "pos_tagService", targetNamespace = "http://pos/", wsdlLocation = "http://localhost:8086/pos?wsdl")
public class PosTagService
    extends Service
{

    private final static URL POSTAGSERVICE_WSDL_LOCATION;
    private final static WebServiceException POSTAGSERVICE_EXCEPTION;
    private final static QName POSTAGSERVICE_QNAME = new QName("http://pos/", "pos_tagService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8086/pos?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        POSTAGSERVICE_WSDL_LOCATION = url;
        POSTAGSERVICE_EXCEPTION = e;
    }

    public PosTagService() {
        super(__getWsdlLocation(), POSTAGSERVICE_QNAME);
    }

    public PosTagService(WebServiceFeature... features) {
        super(__getWsdlLocation(), POSTAGSERVICE_QNAME, features);
    }

    public PosTagService(URL wsdlLocation) {
        super(wsdlLocation, POSTAGSERVICE_QNAME);
    }

    public PosTagService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, POSTAGSERVICE_QNAME, features);
    }

    public PosTagService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PosTagService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PosTag
     */
    @WebEndpoint(name = "pos_tagPort")
    public PosTag getPosTagPort() {
        return super.getPort(new QName("http://pos/", "pos_tagPort"), PosTag.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PosTag
     */
    @WebEndpoint(name = "pos_tagPort")
    public PosTag getPosTagPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://pos/", "pos_tagPort"), PosTag.class, features);
    }

    private static URL __getWsdlLocation() {
        if (POSTAGSERVICE_EXCEPTION!= null) {
            throw POSTAGSERVICE_EXCEPTION;
        }
        return POSTAGSERVICE_WSDL_LOCATION;
    }

}
