
package wiki_infobox;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Main_ConService", targetNamespace = "http://wiki_infobox/", wsdlLocation = "http://localhost:8087/KB?wsdl")
public class MainConService
    extends Service
{

    private final static URL MAINCONSERVICE_WSDL_LOCATION;
    private final static WebServiceException MAINCONSERVICE_EXCEPTION;
    private final static QName MAINCONSERVICE_QNAME = new QName("http://wiki_infobox/", "Main_ConService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8087/KB?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MAINCONSERVICE_WSDL_LOCATION = url;
        MAINCONSERVICE_EXCEPTION = e;
    }

    public MainConService() {
        super(__getWsdlLocation(), MAINCONSERVICE_QNAME);
    }

    public MainConService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MAINCONSERVICE_QNAME, features);
    }

    public MainConService(URL wsdlLocation) {
        super(wsdlLocation, MAINCONSERVICE_QNAME);
    }

    public MainConService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MAINCONSERVICE_QNAME, features);
    }

    public MainConService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MainConService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MainCon
     */
    @WebEndpoint(name = "Main_ConPort")
    public MainCon getMainConPort() {
        return super.getPort(new QName("http://wiki_infobox/", "Main_ConPort"), MainCon.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MainCon
     */
    @WebEndpoint(name = "Main_ConPort")
    public MainCon getMainConPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://wiki_infobox/", "Main_ConPort"), MainCon.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MAINCONSERVICE_EXCEPTION!= null) {
            throw MAINCONSERVICE_EXCEPTION;
        }
        return MAINCONSERVICE_WSDL_LOCATION;
    }

}
